---@diagnostic disable: lowercase-global

midi_mappings = {
  cc0 = { name = "Bank Select (MSB)", ctrlName = ''},
  cc1 = { name = "Modulation Wheel", ctrlName = ''},
  cc2 = { name = "Breath controller", ctrlName = ''},
  cc3 = { name = "Undefined", ctrlName = ''},
  cc4 = { name = "Foot Pedal (MSB)", ctrlName = ''},
  cc5 = { name = "Portamento Time (MSB)", ctrlName = ''},
  cc6 = { name = "Data Entry (MSB)", ctrlName = ''},
  cc7 = { name = "Volume (MSB)", ctrlName = ''},
  cc8 = { name = "Balance (MSB", ctrlName = ''},
  cc9 = { name = "Undefined", ctrlName = ''},
  cc10 = { name = "Pan position (MSB)", ctrlName = ''},
  cc11 = { name = "Expression (MSB) (Expression is a percentage of volume CC7)", ctrlName = ''},
  cc12 = { name = "Effect Control 1 (MSB)", ctrlName = ''},
  cc13 = { name = "Effect Control 2 (MSB)", ctrlName = ''},
  cc14 = { name = "Undefined", ctrlName = ''},
  cc15 = { name = "Undefined", ctrlName = ''},
  cc16 = { name = "Ribbon Controller or General Purpose Slider 1", ctrlName = ''},
  cc17 = { name = "Knob 1 or General Purpose Slider 2", ctrlName = ''},
  cc18 = { name = "General Purpose Slider 3", ctrlName = ''},
  cc19 = { name = "Knob 2 General Purpose Slider 4", ctrlName = ''},
  cc20 = { name = "Knob 3 or Undefined", ctrlName = ''},
  cc21 = { name = "Knob 4 or Undefined", ctrlName = ''},
  cc22 = { name = "Undefined", ctrlName = ''},
  cc23 = { name = "Undefined", ctrlName = ''},
  cc24 = { name = "Undefined", ctrlName = ''},
  cc25 = { name = "Undefined", ctrlName = ''},
  cc26 = { name = "Undefined", ctrlName = ''},
  cc27 = { name = "Undefined", ctrlName = ''},
  cc28 = { name = "Undefined", ctrlName = ''},
  cc29 = { name = "Undefined", ctrlName = ''},
  cc30 = { name = "Undefined", ctrlName = ''},
  cc31 = { name = "Undefined", ctrlName = ''},
  cc32 = { name = "Bank Select (LSB) (see CC0)", ctrlName = ''},
  cc33 = { name = "Modulation Wheel (LSB)", ctrlName = ''},
  cc34 = { name = "Breath controller (LSB)", ctrlName = ''},
  cc36 = { name = "Foot Pedal (LSB)", ctrlName = ''},
  cc37 = { name = "Portamento Time (LSB)", ctrlName = ''},
  cc38 = { name = "Data Entry (LSB)", ctrlName = ''},
  cc39 = { name = "Volume (LSB)", ctrlName = ''},
  cc40 = { name = "Balance (LSB)", ctrlName = ''},
  cc42 = { name = "Pan position (LSB)", ctrlName = ''},
  cc43 = { name = "Expression (LSB)", ctrlName = ''},
  cc44 = { name = "Effect Control 1 (LSB) Roland Portamento on and rate", ctrlName = ''},
  cc45 = { name = "Effect Control 2 (LSB)", ctrlName = ''},
  cc46 = { name = "may be in use as the LSB for controller 14 in some devices", ctrlName = ''},
  cc47 = { name = "may be in use as the LSB for controller 15 in some devices", ctrlName = ''},
  cc48 = { name = "may be in use as the LSB for controller 16 in some devices", ctrlName = ''},
  cc49 = { name = "may be in use as the LSB for controller 17 in some devices", ctrlName = ''},
  cc50 = { name = "may be in use as the LSB for controller 18 in some devices", ctrlName = ''},
  cc51 = { name = "may be in use as the LSB for controller 19 in some devices", ctrlName = ''},
  cc52 = { name = "may be in use as the LSB for controller 20 in some devices", ctrlName = ''},
  cc53 = { name = "may be in use as the LSB for controller 21 in some devices", ctrlName = ''},
  cc54 = { name = "may be in use as the LSB for controller 22 in some devices", ctrlName = ''},
  cc55 = { name = "may be in use as the LSB for controller 23 in some devices", ctrlName = ''},
  cc56 = { name = "may be in use as the LSB for controller 24 in some devices", ctrlName = ''},
  cc57 = { name = "may be in use as the LSB for controller 25 in some devices", ctrlName = ''},
  cc58 = { name = "may be in use as the LSB for controller 26 in some devices", ctrlName = ''},
  cc59 = { name = "may be in use as the LSB for controller 27 in some devices", ctrlName = ''},
  cc60 = { name = "may be in use as the LSB for controller 28 in some devices", ctrlName = ''},
  cc61 = { name = "may be in use as the LSB for controller 29 in some devices", ctrlName = ''},
  cc62 = { name = "may be in use as the LSB for controller 30 in some devices", ctrlName = ''},
  cc63 = { name = "may be in use as the LSB for controller 31 in some devices", ctrlName = ''},
  cc64 = { name = "Hold Pedal (on/off)", ctrlName = ''},
  cc65 = { name = "Portamento (on/off)", ctrlName = ''},
  cc66 = { name = "Sostenuto Pedal (on/off)", ctrlName = ''},
  cc67 = { name = "Soft Pedal (on/off)", ctrlName = ''},
  cc68 = { name = "Legato Pedal (on/off)", ctrlName = ''},
  cc69 = { name = "Hold 2 Pedal (on/off)", ctrlName = ''},
  cc70 = { name = "Sound Variation", ctrlName = ''},
  cc71 = { name = "Resonance (Timbre)", ctrlName = ''},
  cc72 = { name = "Sound Release Time", ctrlName = ''},
  cc73 = { name = "Sound Attack Time", ctrlName = ''},
  cc74 = { name = "Frequency Cutoff (Brightness)", ctrlName = ''},
  cc75 = { name = "Sound Control 6", ctrlName = ''},
  cc76 = { name = "Sound Control 7", ctrlName = ''},
  cc77 = { name = "Sound Control 8", ctrlName = ''},
  cc78 = { name = "Sound Control 9", ctrlName = ''},
  cc79 = { name = "Sound Control 10", ctrlName = ''},
  cc80 = { name = "Decay or General Purpose Button 1 (on/off) Roland Tone level 1", ctrlName = ''},
  cc81 = { name = "Hi Pass Filter Frequency or General Purpose Button 2 (on/off) Roland Tone level 2", ctrlName = ''},
  cc82 = { name = "General Purpose Button 3 (on/off) Roland Tone level 3", ctrlName = ''},
  cc83 = { name = "General Purpose Button 4 (on/off) Roland Tone level 4", ctrlName = ''},
  cc84 = { name = "Portamento Amount", ctrlName = ''},
  cc85 = { name = "Undefined", ctrlName = ''},
  cc86 = { name = "Undefined", ctrlName = ''},
  cc87 = { name = "Undefined", ctrlName = ''},
  cc88 = { name = "Undefined", ctrlName = ''},
  cc89 = { name = "Undefined", ctrlName = ''},
  cc90 = { name = "Undefined", ctrlName = ''},
  cc91 = { name = "Reverb Level", ctrlName = ''},
  cc92 = { name = "Tremolo Level", ctrlName = ''},
  cc93 = { name = "Chorus Level", ctrlName = ''},
  cc94 = { name = "Detune Level", ctrlName = ''},
  cc95 = { name = "Phaser Level", ctrlName = ''},
  cc96 = { name = "Data Button increment", ctrlName = ''},
  cc97 = { name = "Data Button decrement", ctrlName = ''},
  cc98 = { name = "Non-registered Parameter (NRPN) (LSB) (For controllers 6, 38, 96, and 97, it selects the NRPN parameter)", ctrlName = ''},
  cc99 = { name = "Non-registered Parameter (NRPN) (MSB) (For controllers 6, 38, 96, and 97, it selects the NRPN parameter)", ctrlName = ''},
  cc100 = { name = "Registered Parameter (RPN) (LSB) (For controllers 6, 38, 96, and 97, it selects the RPN parameter)", ctrlName = ''},
  cc101 = { name = "Registered Parameter (RPN) (MSB) (For controllers 6, 38, 96, and 97, it selects the RPN parameter)", ctrlName = ''},
  cc102 = { name = "Undefined", ctrlName = ''},
  cc103 = { name = "Undefined", ctrlName = ''},
  cc104 = { name = "Undefined", ctrlName = ''},
  cc105 = { name = "Undefined", ctrlName = ''},
  cc106 = { name = "Undefined", ctrlName = ''},
  cc107 = { name = "Undefined", ctrlName = ''},
  cc108 = { name = "Undefined", ctrlName = ''},
  cc109 = { name = "Undefined", ctrlName = ''},
  cc110 = { name = "Undefined", ctrlName = ''},
  cc111 = { name = "Undefined", ctrlName = ''},
  cc112 = { name = "Undefined", ctrlName = ''},
  cc113 = { name = "Undefined", ctrlName = ''},
  cc114 = { name = "Undefined", ctrlName = ''},
  cc115 = { name = "Undefined", ctrlName = ''},
  cc116 = { name = "Undefined", ctrlName = ''},
  cc117 = { name = "Undefined", ctrlName = ''},
  cc118 = { name = "Undefined", ctrlName = ''},
  cc119 = { name = "Undefined", ctrlName = ''},
  cc120 = { name = "All Sound Off (It does so regardless of release time or sustain. (See MIDI CC 123))", ctrlName = ''},
  cc121 = { name = "All Controllers Off", ctrlName = ''},
  cc122 = { name = "Local Keyboard (on/off)", ctrlName = ''},
  cc123 = { name = "All Notes Off (Release time will still be maintained, and notes held by sustain will not turn off until sustain pedal is depressed.)", ctrlName = ''},
  cc124 = { name = "Omni Mode Off", ctrlName = ''},
  cc125 = { name = "Omni Mode On", ctrlName = ''},
  cc126 = { name = "Mono Operation", ctrlName = ''},
  cc127 = { name = "Poly Mode", ctrlName = ''},
}